name: MeTTaLog CI/CD Workflow

on:
  push:
    branches:
      - main
      - dev
      - metta-log-test

  pull_request:
    branches:
      - main
      - dev
      - metta-log-test

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    container:
      image: indominyus/mettalog:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run mettalog test
        run: |
          pip3 install ansi2html
          python3 scripts/run-tests.py
